version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-minor-versions:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      prod-minor-versions:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
